sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    animation.runImageAnimation(
    myMole,
    assets.animation`moleAnimation`,
    100,
    false
    )
    simplified.moveToRandomHoleOnGrid(myMole)
    music.baDing.play()
    animation.runImageAnimation(
    myHammer,
    assets.animation`hammerAnimation`,
    50,
    false
    )
})
let myHammer: Sprite = null
let myMole: Sprite = null
game.showLongText("The arrow keys are to move the hammer.", DialogLayout.Center)
music.pewPew.play()
game.showLongText("This game sucks not going to lie, so if you hate me, I will come after you. I KNOW WHERE YOU LIVE.", DialogLayout.Center)
music.pewPew.play()
game.showLongText("If you listen to the rules and DON'T break the game, it hopefully won't be too bad.", DialogLayout.Center)
music.pewPew.play()
game.showLongText("Also make sure to have as much fun as possible! (TRY PLS)", DialogLayout.Bottom)
music.pewPew.play()
game.showLongText("Try to get more than 50, or you suck!", DialogLayout.Bottom)
music.pewPew.play()
game.showLongText("Also, remember you are ruining its life. You will do this professionally.", DialogLayout.Bottom)
scene.setBackgroundImage(assets.image`grid0`)
myMole = sprites.create(assets.image`mole`, SpriteKind.Enemy)
myHammer = sprites.create(img`
    .................77.............
    ...............7722ee...........
    ...............7722ee...........
    .............7722eeeeee.........
    .............7722eeeeee.........
    ...........7722eeeeeeeeee.......
    ...........7722eeeeeeeeee.......
    .........7722eeeeeeeeeeeeee.....
    .........7722eeeeeeeeeeeeee.....
    ...........eeeeeeeeeeeeeeeeee...
    ...........eeeeeeeeeeeeeeeeee...
    .............eeeeeeeeeeeeeebb11.
    .............eeeeeeeeeeeeeebb11.
    .............ccddeeeeeeeebb11...
    .............ccddeeeeeeeebb11...
    ...........ccddbbeeeeeebb11.....
    ...........ccddbbeeeeeebb11.....
    .........ccddbb....eebb11.......
    .........ccddbb....eebb11.......
    .......ccddbb........11.........
    .......ccddbb........11.........
    .....ccddbb.....................
    .....ccddbb.....................
    ...ccddbb.......................
    ...ccddbb.......................
    .ccddbb.........................
    .ccddbb.........................
    .ddbb...........................
    .ddbb...........................
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
simplified.moveOnlyOnscreenWithArrows(myHammer, simplified.Speeds.Fast)
carnival.addLabelTo("Whack-the-Mole", carnival.Areas.Bottom)
carnival.startCountdownGame(30, carnival.WinTypes.Multi)
game.onUpdateInterval(1000, function () {
    simplified.moveToRandomHoleOnGrid(myMole)
})
forever(function () {
    music.play(music.stringPlayable("C5 G G E D A - - ", 120), music.PlaybackMode.UntilDone)
    music.play(music.stringPlayable("C5 G G E D C5 - - ", 120), music.PlaybackMode.UntilDone)
})
